spring:
  application:
    name: todoService
  datasource:
    url: jdbc:mysql://${MYSQL_NAME}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

server:
  port: 8080
  servlet:
    context-path: /todo
  forward-headers-strategy: framework

logging:
  level:
    com.mock.todo: info

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    use-root-path: true
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false

authorization:
  keyName: "X-API-KEY"
  authValue: ${SERVICE_SECRET}
