spring:
  application:
    name: todoService
  datasource:
    url: jdbc:mysql://${MYSQL_NAME}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /todo
